name = "auto-reaction-bot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "7256695013:AAFFObtXBionF0JUsvVgtqiRZ3jEigTOPOo"
BOT_USERNAME = "realmreact_bot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RESTRICTED_CHATS = "1234,5678"
